### ISSUE TITLE
Loading class fails with _.toMap is not a function

### ISSUE THREAD

**Issue by dselman** [kylestev/jvm.js#33]
```
(node:20881) UnhandledPromiseRejectionWarning: TypeError: _.toMap is not a function
    at ClassLoader.loadClasses (/Users/dselman/dev/javacto/node_modules/jvm/lib/core/ClassLoader.js:147:34)
    at /Users/dselman/dev/javacto/node_modules/jvm/lib/core/Jar.js:138:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kylestev** [comment]
Fixed in 64bc877a. Thanks for the report! Release tagged at [0.4.0](https://github.com/kylestev/jvm.js/releases/tag/v0.4.0)
